version: "3"
services:
  web:
    container_name: web
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongo:27017/comp308_Auth
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
